- name: VACATION RENTALS 
  description: For those seeking a more private and personalized experience, we provide rentals ranging from quaint cottages to spacious villas. These rentals offer the flexibility and peak comfort, ideal for families, groups, or anyone looking for a unique stay experience. 

- name: EXPERIENCES 
  description: We believe that travel is about more than just accommodation—it's about creating lasting memories. Which is why we offer a variety of curated experiences to complement your stay. Wahtever your interest, we have something for you. 

# - name: SPECIAL PACKAGES 
#   description: 
  
- name: ACCOMMODATION BOOKING 
  description: Whether you're looking for a cozy homestay nestled in the hills or a luxurious resort by the beach, we've got you covered. Our platform features a diverse selection of accommodations, including homestays, resorts, and guesthouses, across Karnataka. 

- name: VACATION RENTALS 
  description: To make your trip even more convenient and enjoyable, we offer special packages tailored to different interests and preferences. These packages include accommodation, meals, and curated experiences, providing a hassle-free way to explore Karnataka. 

- name: CONCIERGE SERVICES 
  description: Our dedicated concierge team is available to assist you every step of the way, from planning your itinerary to arranging transportation. Be it restaurant recommendations, transportation, or local insights, our team ensures a seamless and memorable travel experience. 

- name: ONLINE BOOKING PLATFORM 
  description: Our user-friendly online platform makes it easy to browse, book, and manage your reservations from the comfort of your own home. With realtime availability, secure payment options, and instant confirmation, booking with Ghatstays is quick, convenient, and reliable. 

- name: CUSTOMER SUPPORT 
  description: We pride ourselves on providing excellent customer support to ensure that your experience with Ghatstays is smooth and stress-free. Our customer support team is available to assist you with any queries or concerns before, during, and after your trip.